### PR TITLE
Lots of modifications, feel free to accept them

### PR DESCRIPTION
**Pull request by wfsaxton**
Not sure if you are accepting pull requests, but I took a look @ your work and figured I could build off of it for my own needs.  

My own commits comments don't really do it justice because my first commit included a ton of changes.  Here's the highlights:

* Added a Vagrantfile so a user can create a simple ansible control host
* Added support for Fedora (tested on Fedora 25)
  * NOTE: I did not test these changes on Ubuntu, but if you could take a look and make sure it works that would be great)
* Added multi-site support
  * Instead of just using /var/www/html, it will now use /var/www/{{ domain }}/grav-admin for each domain's document root; also, /etc/nginx/sites-available will contain the file name {{ domain }} instead of default.
* Removed all references to "raw.githubusercontent.com"
  * I moved all of those files into either the file directory, if it just required a file copy, or templates, if I converted it to a jinja template.  Templates allow you to put variables in files so you don't have to do those regex substitution commands you were doing
* Appended ".tmpl" to the "ansible.cfg" and "hosts" files
  * This allowed me to keep those files as references checked in but anyone using this code can simply copy them to "ansible.cfg" and "hosts" and modify them.  I put them in the .gitignore so they wouldn't we checked in.

### CODE REVIEW

**Comment by andywimmer** [comment]
Thanks for the pull request. I'm still learning Ansible obviously and your modifications help with that education so thank you!

I'll check out your changes locally and run some QA before merging this in. Cheers!

**Comment by wfsaxton** [comment]
Okay great.  I'm new to Ansible as well and this has been a good learning experience.

I'm thinking of splitting this up into 2 different playbooks.  One for the server provisioning, which only needs to be run each time you want a new server, and a second one for actual website deployment.  Not sure what the "best practice" is for app deployment, but if that sounds useful let me know.  Otherwise, I can just code my own thing.

**Comment by andywimmer** [comment]
Yeah this started out as just a way for me to learn Ansible with some tangible results; a working Grav installation as opposed to the default Nginx placeholder page. One thing I wanted to get sorted early was support for multiple distros and you have definitely set me down the right path there, so thank you.

I like to keep things simple and basic, so I think the goal of this repo will be basic server setup and Grav installation.

You are definitely welcome to 'code your own thing' though if you'd like to take things further!! 😃

**Comment by wfsaxton** [comment]
Okay, sounds good.  I'm not sure how to "stop" adding my commits to this pull request, but I'm about to start making those changes for separate playbooks.  Are you still considering this pull request or do you just want to use my fork as a reference and can pull in the stuff later?

**Comment by andywimmer** [comment]
I think I'm going to use your fork as reference and pull in changes as I have time to QA them.

**Comment by wfsaxton** [comment]
kk

**Pull request closed without merging**
